### PR TITLE
Feature/follow upcreare conturi

### PR DESCRIPTION
**Pull request by R4du911**

### CODE REVIEW

**Comment by Piciorus** [comment]
you can add a print screen to see how looks like

**Comment by R4du911** [comment]
image

**Comment by Piciorus** [comment]
it would be nice to change the roles dropdown to be similar to the other inputs

**Comment by R4du911** [comment]
image

Changed the roles dropdown to be similar to the other inputs

**Review by Piciorus — DISMISSED** [review]

**Review by DragosPetri — DISMISSED** [review]

**Review by VladP2002 — DISMISSED** [review]

**Review by VladP2002 — DISMISSED** [review]

**Pull request merged**
